### ISSUE TITLE
Don't mangle @keyframes decimal breakpoints

### ISSUE THREAD

**Issue by nex3** [google/postcss-rename#53]
This currently mangles `@keyframes` breakpoints that contain decimal points. For example, with `strategy: "debug"`, it converts:

```css
@keyframes name {
  0.1% {opacity: 0.1}
}
```

into

```css
@keyframes name {
  0.\31\%_ {opacity: 0.1}
}
```
