### ISSUE TITLE
Some CSS properties are broken when use postcss-rename

### ISSUE THREAD

**Issue by RodrigoTomeES** [google/postcss-rename#62]
Hi,

I am trying this postcss plugin with tailwind and I found that `postcss-rename` are broken some properties. I have a reproduction in this repo: https://github.com/RodrigoTomeES/awa-db/tree/feature/optimize-classes

To test it you only need:

```bash
yarn install
yarn build
```

In `./dist/_astro/` folder you can found the CSS file and in the root of the project should be has the file with the map.

You should see things like this:

```css
@media (min-width: 768px) {
  .ub {
    t-template-columns: repeat(3, minmax(0, 1fr));
  }
  .vb {
    font-size: 3rem;
    line-height: 1.625;
  }
}

.O {
  s-radius: 0.35rem;
}
```
